new file:   README.md 	modified:   bin/spam 	deleted:    spam.spk 	new file:   spam/spam.spk

diff --git a/bin/spam b/bin/spam
--- a/bin/spam
+++ b/bin/spam
@@ -1,6 +1,7 @@
 #!/bin/bash
 sleep 1
 spam_ver=1.10cb1
+
 pause() {
     prompt="$1"
     echo -e -n "\033[1;36m$prompt"
@@ -49,8 +50,24 @@ pkglist () {
 ls $HOME/.spam/pkg
 }
 
+pkgdel () {
+  pkg=$1
+   if [ ! -e "$HOME/.spam/pkg/${pkg}" ]; then
+     echo "$pkg is not on your computer."
+   else
+     echo "Removing $1..."
+     rm -rf $HOME/.spam/bin/$(ls $HOME/.spam/pkg/$pkg/bin)
+     rm -rf $HOME/.spam/pkg/$pkg
+     echo "Done!"
+   fi
+}
+
  pkguse () {
   pkg=${1/*\/}
+  if [[ -z $1 ]]; then
+   echo No command found.
+   exit 1
+  fi
    if [ -e "$HOME/.spam/pkg/${pkg}" ]; then
      echo "$pkg is already on your computer."
    else
@@ -61,7 +78,7 @@ ls $HOME/.spam/pkg
      if [[ -f "$pkgpath/$pkg.spk" ]]; then
       mkdir -p $pkgbox
       tar xvf $pkgpath/$pkg.spk -C $pkgbox
-      ln -s $pkgbox/bin/* $spam/bin
+      ln -s $pkgbox/bin/* $HOME/.spam/bin
       rm -rf $pkgpath
       echo "Done!"
      else
@@ -71,20 +88,48 @@ ls $HOME/.spam/pkg
    fi
  }
 
+ rkguse () {
+  pkg=$2
+  repo=$1
+  if [[ -z $1 ]]; then
+   echo No command found.
+   exit 1
+  fi
+   if [ -e "$HOME/.spam/pkg/${pkg}" ]; then
+     echo "$pkg is already on your computer."
+   else
+     echo "Installing $2 from $1..."
+     git clone https://github.com/$1 ~/.spam/usr/pkgcache/repo-$repo/$pkg
+     repopath="$HOME/.spam/usr/pkgcache/repo-$repo/$pkg"
+     pkgbox="$HOME/.spam/pkg/$pkg"
+     if [[ -f "$repopath/spam/$pkg.spk" ]]; then
+      mkdir -p $pkgbox
+      tar xvf $repopath/spam/$pkg.spk -C $pkgbox
+      ln -s $pkgbox/bin/* $HOME/.spam/bin
+      rm -rf $repopath
+      echo "Done!"
+     else
+       echo "A fatal error occured."
+       rm -rf $repopath
+     fi
+   fi
+ }
+
+
 if [[ "$1" == "-h" || "$1" == "--help" ]]; then
 	help
 elif [[ "$1" == "-v" || "$1" == "--version" ]]; then
 	version
 elif [[ "$1" == "remove" ]]; then
-	uninstall
+	pkgdel $2
 elif [[ "$1" == "selfupgrade" ]]; then
 	update
 elif [[ "$1" == "install" ]]; then
- 	if [[ -z $2 ]]; then
- 		pkglist
- 	else
- 		pkguse $2
- 	fi
+ 	pkguse $2
+elif [[ "$1" == "list" ]]; then
+	pkglist
+elif [[ "$1" == "installrepo" ]]; then
+        rkguse $2 $3
 else
 	nocommand
 fi
